apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: reflector
spec:
  chart:
    spec:
      # renovate: registryUrl=https://emberstack.github.io/helm-charts/
      chart: reflector
      version: 5.4.17
      sourceRef:
        kind: HelmRepository
        name: emberstack
        namespace: flux-system
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  install:
    remediation:
      retries: 3
  interval: 5m
  releaseName: reflector
