---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: my-helm-charts
  namespace: flux-system
spec:
  interval: 10m
  url: https://github.com/gperezmz/helm-charts
  ref:
    branch: main
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/charts/
