---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
spec:
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: home-assistant
      version: 9.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    image:
      repository: homeassistant/home-assistant
      tag: 2021.6.4

    env:
      TZ: Europe/Madrid

    hostNetwork: true

    ingress:
      main:
        enabled: true
        ingressClassName: traefik
        hosts:
          - host: homeassistant.perezmz.com
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: perezmz-com-tls

    persistence:
      config:
        enabled: true
        type: hostPath
        hostPath: /data/home-assistant
        mountPath: /config

    podSecurityContext:
      fsGroup: 1001
