---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx-internal
  namespace: ingress-system
spec:
  chart:
    spec:
      # renovate: registryUrl=https://kubernetes.github.io/ingress-nginx
      chart: ingress-nginx
      version: 3.23.0
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  install:
    remediation:
      retries: 3
  interval: 5m0s
  values:
    controller:
      ingressClass: internal
      replicaCount: 1
      extraEnvs:
        - name: TZ
          value: Europe/Madrid
      service:
        type: LoadBalancer
        externalIPs:
          - 192.168.2.10
        externalTrafficPolicy: Local
      publishService:
        enabled: true
      config:
        ssl-protocols: TLSv1.3 TLSv1.2
        use-proxy-protocol: "false"
        proxy-body-size: "0"
        use-forwarded-headers: "true"
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
          namespace: ingress-system
          namespaceSelector:
            any: true
      extraArgs:
        default-ssl-certificate: ingress-system/perezmz-com-tls
    defaultBackend:
      enabled: false
