---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: dev-vm-hd
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 15Gi
  hostPath:
    path: /data/vms/dev-vm
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dev-vm-hd
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 15Gi
  storageClassName: local-storage
  volumeName: dev-vm-hd
