---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bazarr
  namespace: media
spec:
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: bazarr
      version: 9.3.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 5m0s
  install:
    remediation:
      retries: 3
  values:
    image:
      repository: ghcr.io/k8s-at-home/bazarr
      tag: v0.9.5

    env:
      TZ: Europe/Madrid

    ingress:
      main:
        enabled: true
        ingressClassName: traefik
        annotations:
          traefik.ingress.kubernetes.io/router.middlewares: traefik-forward-auth@kubernetescrd
        hosts:
          - host: bazarr.perezmz.com
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: perezmz-com-tls

    persistence:
      config:
        enabled: true
        type: hostPath
        hostPath: /data/bazarr
        mountPath: /config
      movies:
        enabled: true
        type: hostPath
        hostPath: /mnt/storage/media/movies
        mountPath: /movies
      tv:
        enabled: true
        type: hostPath
        hostPath: /mnt/storage/media/tv
        mountPath: /tv

    podSecurityContext:
      runAsUser: 65534
      runAsGroup: 65534
      fsGroup: 65534
