apiVersion: v1
kind: PersistentVolume
metadata:
  name: bitwardenrs-config
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  hostPath:
    path: /data/bitwardenrs
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitwardenrs-config
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-storage
  volumeName: bitwardenrs-config
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bitwardenrs
spec:
  chart:
    spec:
      chart: bitwardenrs
      version: 0.1.5
      sourceRef:
        kind: HelmRepository
        name: gissilabs
        namespace: flux-system
  install:
    remediation:
      retries: 3
  interval: 1h0m0s
  releaseName: bitwardenrs
  values:
    bitwardenrs:
      admin:
        enabled: false
      allowSignups: false
      domain: https://pw.perezmz.com
      log:
        file: /data/bitwardenrs.log
        level: warn
      smtp:
        enabled: false
      yubico:
        enabled: false
    database:
      type: sqlite
      wal: true
    image:
      repository: bitwardenrs/server
      tag: 1.18.0
    ingress:
      annotations:
        kubernetes.io/ingress.class: external
      enabled: true
      host: pw.perezmz.com
      tls:
      - hosts:
        - pw.perezmz.com
        secretName: perezmz-com-tls
    persistence:
      enabled: true
      existingClaim: bitwardenrs-config
    podSecurityContext:
      fsGroup: 1001
    securityContext:
      runAsGroup: 1001
      runAsUser: 1001
