apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
spec:
  releaseName: home-assistant
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: home-assistant
      version: 5.4.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    image:
      repository: homeassistant/home-assistant
      tag: 2021.1.4

    env:
      TZ: Europe/Madrid

    hostNetwork: true

    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: internal
      hosts:
        - host: homeassistant.perezmz.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - homeassistant.perezmz.com
          secretName: perezmz-com-tls

    persistence:
      config:
        enabled: true
        existingClaim: default-data
        subPath: home-assistant

    podSecurityContext:
      fsGroup: 1001