apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
spec:
  releaseName: redis
  chart:
    spec:
      chart: ./charts/redis
      version: '1.x'
      sourceRef:
        kind: GitRepository
        name: my-helm-charts
        namespace: flux-system
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    image:
      repository: redis
      tag: 6.0.10-alpine

    persistence:
      data:
        enabled: true
        mountPath: /data
        existingClaim: default-data
        subPath: redis

    securityContext:
      runAsGroup: 1001
      runAsUser: 1001

    podSecurityContext:
      fsGroup: 1001