---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: my-websites
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: ssh-credentials
  url: ssh://git@github.com/gperezmz/k8s-websites
  ignore: |
    # exclude file extensions
    /**/.gitignore
    /**/*.md
    /**/*.txt
