---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: media
spec:
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: qbittorrent
      version: 8.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 5m0s
  install:
    remediation:
      retries: 3
  values:
    image:
      repository: ghcr.io/k8s-at-home/qbittorrent
      tag: v4.3.3

    env:
      TZ: Europe/Madrid

    service:
      additionalServices:
        - enabled: true
          nameSuffix: bittorrent
          type: LoadBalancer
          externalIPs:
            - 192.168.2.20
          port:
            port: 51413
            name: bittorrent
            protocol: TCP
          externalTrafficPolicy: Local

    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        traefik.ingress.kubernetes.io/router.middlewares: traefik-authelia@kubernetescrd
      hosts:
        - host: qbittorrent.perezmz.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: perezmz-com-tls

    additionalVolumes:
      - name: qbittorrent-scripts
        configMap:
          name: qbittorrent-scripts
          defaultMode: 511
      - name: data
        persistentVolumeClaim:
          claimName: media-data
      - name: storage
        persistentVolumeClaim:
          claimName: media-storage

    additionalVolumeMounts:
      - mountPath: /config/custom-cont-init.d
        name: qbittorrent-scripts
      - name: data
        mountPath: /config
        subPath: qbittorrent
      - name: data
        mountPath: /downloads
        subPath: downloads

    podSecurityContext:
      runAsUser: 1001
      runAsGroup: 1001
      fsGroup: 1001
