---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: media
spec:
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: qbittorrent
      version: 11.1.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 5m0s
  install:
    remediation:
      retries: 3
  values:
    image:
      repository: ghcr.io/k8s-at-home/qbittorrent
      tag: v4.3.5

    env:
      TZ: Europe/Madrid

    service:
      bittorrent:
        enabled: true
        type: LoadBalancer
        externalIPs:
          - 192.168.2.20
        externalTrafficPolicy: Local
        ports:
          bittorrent:
            enabled: true
            port: 6881
            protocol: TCP
            targetPort: 6881

    ingress:
      main:
        enabled: true
        ingressClassName: traefik
        annotations:
          traefik.ingress.kubernetes.io/router.middlewares: traefik-forward-auth@kubernetescrd
        hosts:
          - host: qbittorrent.perezmz.com
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: perezmz-com-tls

    persistence:
      config:
        enabled: true
        type: hostPath
        hostPath: /data/qbittorrent
        mountPath: /config
      downloads:
        enabled: true
        type: hostPath
        hostPath: /data/downloads
        mountPath: /downloads

    podSecurityContext:
      runAsUser: 1001
      runAsGroup: 1001
      fsGroup: 1001
