apiVersion: v1
kind: Secret
metadata:
    name: grafana-credentials
    namespace: monitoring
stringData:
    admin-password: ENC[AES256_GCM,data:BkgiMfyoZyCzFjSkf6g=,iv:aM8bnSlOUDx0Nb1dzNlFE+MzSpwMJYhNdX1/mx0NFYE=,tag:M5yzz2cRSpV3z9abdAmUrg==,type:str]
    admin-user: ENC[AES256_GCM,data:8S7LP8U=,iv:AmMYRKDoPVCkbfSzG2CK3SccdDY05n6wVXF2xqA72mI=,tag:j2VcxWKAWauJZU9ttB9DFg==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-02-10T05:20:12Z'
    mac: ENC[AES256_GCM,data:2Bx4GPTxjsNpRrvspBRxAWC08lma/G5Ty5W3/CYS3W966jvR25TdrBwRJWKCDlslu7g8jC4UMwjAQAB92xknIx8UTU+Km3Dr4babgL88DDWkjVPWwxFT6jdToPt1zs7t6ANPY51kU4a46peMXdoAm5YzeTGh1aLqtgGX3UAxx54=,iv:RwNXubEbpyoON3bnuX7pyHafSitEOI5hTt898CEsxxw=,tag:zqdrEOLMA2k/K51C+yBr9A==,type:str]
    pgp:
    -   created_at: '2021-02-10T05:20:11Z'
        enc: "-----BEGIN PGP MESSAGE-----\r\n\r\nhQGMAz2OwhEturU+AQwAp9jXXXF/lx968SBbiz4uvmYrM9vb6lX7mXAMV95hZz5p\r\n39Q/CaBrdxS9EW2uoh5sSVB+H3xE9S2qwWRB7M8dpDBN4AJbWByQ83VgpPBKN0mq\r\nnqLj5UOKvmhMKy8up2VuIGj8yjkarSPNhSEleb0aA8RL0lEP36PN0RADPkJf93de\r\nYExuMCsVqqQGt5ZrJQdvqe8vi21SUWp472vjyXWsMQ5hjgZRCIhIsy3A/aBR7aq0\r\nKp9uo3S5zk/fvrHJBjHuvGm5k5ApuaXIEx6bMkSIt0AUY8673j4Q1Pc8+zV5Bxu3\r\ndqWNeKc1SiV8jRloJod1BjgW/EUBP1Z6VSTC26UrV2QlpHl/DGU3zVGjpbDpIhmi\r\ngd1U7Fscen0S57TwmU13V/K/UTmHhYSvG6lT54gbxNxYflzuoxeHXJ0DyOiBdQTI\r\nF6HRbI0WSUIPT9Rw80sSKzmQvPvIQ1ueWmTxNaU9Rt3LCzKpFVHYVMIWWwmz4UQn\r\nZ9hQvfLUyH2fqKqOO6M/0lwByqluGLgBeW0/ILgLfyghjQUaJV1EXNst/vGpK/Bu\r\npS9O66OmhPQqJH9rLupxtZN5uOkJZqMIFzD7NOXZttKsou2SqMeEGeCyyR8RPOID\r\n4iC4nCPD/zqCYN9Mvg==\r\n=IRU3\r\n-----END
            PGP MESSAGE-----\r\n"
        fp: B95DBC80D9BD192B0811AC61BB73E1527E549D6C
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
