---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: samba
  namespace: media
spec:
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: samba
      version: 2.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 5m0s
  install:
    remediation:
      retries: 3
  values:
    image:
      repository: dperson/samba
      tag: latest

    env:
      TZ: Europe/Madrid
      USERID: 1001
      GROUPID: 1001

    envFrom:
      - configMapRef:
          name: samba-config
      - secretRef:
          name: samba-users

    service:
      type: LoadBalancer
      externalIPs:
        - 192.168.2.40
      externalTrafficPolicy: Local

    additionalVolumes:
      - name: storage
        persistentVolumeClaim:
          claimName: media-storage

    additionalVolumeMounts:
      - name: storage
        mountPath: /documents
        subPath: documents
      - name: storage
        mountPath: /media
        subPath: media
      - name: storage
        mountPath: /shares
        subPath: shares

    podSecurityContext:
      fsGroup: 1001
