---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: traefik-crd-source
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://github.com/traefik/traefik-helm-chart.git
  ref:
    # renovate: registryUrl=https://helm.traefik.io/traefik chart=traefik
    tag: v9.20.1
  ignore: |
    # exclude all
    /*
    # include deploy crds dir
    !/traefik/crds/
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: traefik-crd
  namespace: flux-system
spec:
  interval: 5m0s
  prune: false
  sourceRef:
    kind: GitRepository
    name: traefik-crd-source
  timeout: 2m
