apiVersion: v1
data:
  USER: ENC[AES256_GCM,data:twHEclCt07nxFvDvFAcjC5trbDqFh48C,iv:v9cbfz3/8xYXR0ydY1Iqs9ym/pknJVPOJlMWbMIHvJg=,tag:kRUqjkZWNyCOk2+gxmYOhw==,type:str]
  USER2: ENC[AES256_GCM,data:9JZXaLwG6RXei1IRzP3SxXvCkxKO6u5wDe7v2A==,iv:BvjEX0JYmI2/4sMtFUAtu674yKNjVc2xYeUHRlLIVBs=,tag:UiZMDZbnnRb5NVQQOnd4Iw==,type:str]
kind: Secret
metadata:
  creationTimestamp: null
  name: samba-users
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  lastmodified: "2021-01-13T21:40:27Z"
  mac: ENC[AES256_GCM,data:7ZBtWlwq9LrdJBo2zTjyt5cKKq/QLXpNqJz7/TuywgVTrPiQ6zRJZVbiJT6EIqewc8tAMUPQEDVxURhWTgQMIsU4giNALkInGeZqxbYTZ85BGxeGfVH5kv5mbDX8SxpTuXHaQPZ584sTt0Q7C7FZdi8N5MUa/hJfchUmpRW3fNo=,iv:CEXzIb2/f5LxE+uzpDhYTrEQX8KyRjWK/esUa7PPY9Y=,tag:UczKZJoP5oYwtgoqiN6hSg==,type:str]
  pgp:
    - created_at: "2021-01-13T21:40:26Z"
      enc:
        "-----BEGIN PGP MESSAGE-----\r\n\r\nhQGMAz2OwhEturU+AQv7B+7lT6T4BzX4LwIMy3K3PYTvcUuelaQyqsCLHpew1z8U\r\nq/Wu2USoCey+mW8MKfwkie/RYTY3QFScJzXUmF2YbBg8CB3IgvUa9ddYWXr0ZZeP\r\nHJ2N5fR+jDtW8VeS3r6CIys9zdWwFWf5FCcFAQjYrRKJCEoaGT6cdT+V+eRpbdba\r\nXnAN70PBLhQRclsbH4WV5Q1GqqTWv8M5df/kscguMDlZeez92D6PX+4L7mCkUJ0e\r\nQ43YwIMX+oUFMYh14sudryBUljzkrl+y9lejUBQxTB4Up8EGc1g7mQ4A8fa/vIge\r\nYS7peSt763GwOs8KlxSNxa4fWHuZRpHJXAju6B6pKOkeda8lsUqDBHsqDWMb6IyY\r\nWyUGMmaVds8VmVCAXF1D1MSDW3eb34bI7jB5c4D+6DJEwOUSxmTyqL+TZaU+y1t+\r\nodpcN8R6gxNM3jIPktRRsucFWftaPW08KyejiwJ4ryj3y0+pCxWEiPtrtQiWy8Eu\r\n7ePOn7MPtPUUGoZT1wGR0l4BOs7EkrWuzYOY6AG6iYzjLxZL4vrgvtaH/LROKiZI\r\ns8/1YoMb+z18a3KvTc8raVrXdL0VlJSEBUBafcb3rwyup9i6nY2Er26Zc8Ug7dDY\r\nPd3mO2hpgV4Lz+0/QxBI\r\n=MAcj\r\n-----END
        PGP MESSAGE-----\r\n"
      fp: B95DBC80D9BD192B0811AC61BB73E1527E549D6C
  encrypted_regex: ^(data|stringData)$
  version: 3.6.1
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: samba-config
data:
  NMBD: "true"
  PERMISSIONS: "true"
  RECYCLE: "true"
  SHARE: Media;/media;yes;no;no;all
  SHARE2: Public;/shares/public;yes;no;no;all
  SHARE3: Kitty;/shares/kitty;yes;no;no;kitty
  SHARE4: Guillermo;/shares/gperezmz;yes;no;no;gperezmz
  SHARE5: Documents;/documents;yes;no;no;all
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: samba
spec:
  releaseName: samba
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: samba
      version: 1.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 10m
  install:
    remediation:
      retries: 3
  values:
    image:
      repository: dperson/samba
      tag: latest

    env:
      TZ: Europe/Madrid
      USERID: 1001
      GROUPID: 1001

    envFrom:
      - configMapRef:
          name: samba-config
      - secretRef:
          name: samba-users

    service:
      type: LoadBalancer
      externalIPs:
        - 192.168.2.40
      externalTrafficPolicy: Local

    additionalVolumes:
      - name: storage
        persistentVolumeClaim:
          claimName: media-storage

    additionalVolumeMounts:
      - name: storage
        mountPath: /documents
        subPath: documents
      - name: storage
        mountPath: /media
        subPath: media
      - name: storage
        mountPath: /shares
        subPath: shares

    podSecurityContext:
      fsGroup: 1001
