---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: media
spec:
  releaseName: sonarr
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: sonarr
      version: 8.2.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    image:
      repository: ghcr.io/hotio/sonarr
      tag: nightly-3.0.4.1096

    env:
      TZ: Europe/Madrid
      PUID: 1001
      PGID: 1001

    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: internal

        nginx.ingress.kubernetes.io/auth-url: "http://authelia.ingress-system.svc.cluster.local:9091/api/verify"
        nginx.ingress.kubernetes.io/auth-signin: "https://login.perezmz.com"
      hosts:
        - host: sonarr.perezmz.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - sonarr.perezmz.com
          secretName: perezmz-com-tls

    additionalVolumes:
      - name: data
        persistentVolumeClaim:
          claimName: media-data
      - name: storage
        persistentVolumeClaim:
          claimName: media-storage

    additionalVolumeMounts:
      - name: data
        mountPath: /config
        subPath: sonarr
      - name: data
        mountPath: /downloads
        subPath: downloads
      - name: storage
        mountPath: /tv
        subPath: media/tv
