---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: claywith-me
  namespace: cert-manager
  annotations:
    reflector.v1.k8s.emberstack.com/secret-reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/secret-reflection-auto-enabled: "true"
spec:
  commonName: claywith.me
  dnsNames:
    - claywith.me
    - "*.claywith.me"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production
  secretName: claywith-me-tls
