apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: etcd
  namespace: kube-system
spec:
  releaseName: etcd
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: etcd
      version: 5.5.1
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    statefulset:
      replicaCount: 1
    auth:
      rbac:
        enabled: false
    persistence:
      enabled: false
