---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: kube-system
  namespace: flux-system
spec:
  dependsOn:
    - name: flux-system-bootstrap
  interval: 10m0s
  path: ./kube-system
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
