---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: monitoring-system
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  dependsOn:
    - name: flux-system-bootstrap
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v1beta1
      kind: HelmRelease
      name: kube-prometheus-stack
      namespace: monitoring-system
    - apiVersion: helm.toolkit.fluxcd.io/v1beta1
      kind: HelmRelease
      name: victoria-metrics-operator
      namespace: monitoring-system
  interval: 10m0s
  path: ./monitoring-system
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
