---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dex
spec:
  chart:
    spec:
      # renovate: registryUrl=https://charts.dexidp.io
      chart: dex
      version: 0.3.2
      sourceRef:
        kind: HelmRepository
        name: dex
        namespace: flux-system
  install:
    remediation:
      retries: 3
  interval: 5m0s
  values:
    config:
      issuer: https://dex.perezmz.com

      enablePasswordDB: false

      oauth2:
        responseTypes: ["code", "token", "id_token"]
        skipApprovalScreen: true

      storage:
        type: kubernetes
        config:
          inCluster: true

    service:
      port: 5556

    ingress:
      enabled: true
      className: traefik
      hosts:
        - host: dex.perezmz.com
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: perezmz-com-tls
  valuesFrom:
    - kind: Secret
      name: dex-helm-values
