---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unifi
spec:
  chart:
    spec:
      chart: ./charts/unifi
      version: 1.x
      sourceRef:
        kind: GitRepository
        name: my-helm-charts
        namespace: flux-system
  interval: 5m0s
  install:
    remediation:
      retries: 3
  values:
    image:
      repository: jacobalberty/unifi
      tag: 6.1.71-rc

    env:
      TZ: Europe/Madrid
      RUNAS_UID0: "false"
      UNIFI_UID: 1001
      UNIFI_GID: 1001
      UNIFI_STDOUT: "true"

    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        traefik.ingress.kubernetes.io/service.serversscheme: https
      hosts:
        - host: unifi.perezmz.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: perezmz-com-tls

    persistence:
      unifi:
        enabled: true
        existingClaim: default-data
        subPath: unifi
