---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jackett
  namespace: media
spec:
  releaseName: jackett
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: jackett
      version: 6.3.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    image:
      repository: ghcr.io/hotio/jackett
      tag: release-0.17.354

    env:
      TZ: Europe/Madrid
      PUID: 1001
      PGID: 1001

    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: internal

        nginx.ingress.kubernetes.io/auth-url: "http://authelia.ingress-system.svc.cluster.local:9091/api/verify"
        nginx.ingress.kubernetes.io/auth-signin: "https://login.perezmz.com"
      hosts:
        - host: jackett.perezmz.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - jackett.perezmz.com
          secretName: perezmz-com-tls

    persistence:
      config:
        enabled: true
        existingClaim: media-data
        subPath: jackett
