---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: plex
      version: 4.3.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 5m0s
  install:
    remediation:
      retries: 3
  values:
    image:
      repository: ghcr.io/k8s-at-home/plex
      tag: v1.22.3.4392-d7c624def

    env:
      TZ: Europe/Madrid
      ADVERTISE_IP: https://plex.perezmz.com:443/,http://192.168.2.21:32400/
      ALLOWED_NETWORKS: 192.168.0.0/22,10.42.0.0/16
      PLEX_PREFERENCE_1: LanNetworkBandwith=192.168.0.0/22\,10.42.0.0/16

    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        traefik.ingress.kubernetes.io/router.middlewares: traefik-forward-auth@kubernetescrd
      hosts:
        - host: plex.perezmz.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: perezmz-com-tls

    additionalVolumes:
      - name: data
        persistentVolumeClaim:
          claimName: media-data
      - name: storage
        persistentVolumeClaim:
          claimName: media-storage

    additionalVolumeMounts:
      - name: data
        mountPath: /config
        subPath: plex
      - name: data
        mountPath: /transcode
        subPath: plex-transcode
      - name: storage
        mountPath: /data
        subPath: media

    podSecurityContext:
      runAsUser: 1001
      runAsGroup: 1001
      fsGroup: 1001
