---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: bitwardenrs-backup-db
spec:
  schedule: "*/30 * * * *"
  failedJobsHistoryLimit: 3
  successfulJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          securityContext:
            runAsGroup: 1001
            runAsUser: 1001
            fsGroup: 1001
          initContainers:
            - name: busybox-shell
              image: busybox
              args:
                - /bin/sh
                - -c
                - "(mkdir /data/backups || true) && (cd /data/backups && ls -tp | grep -v '/$' | tail -n +6 | xargs -I {} rm -- {})"
              volumeMounts:
                - mountPath: /data
                  name: bitwardenrs-config
          containers:
            - name: sqlite3
              image: keinos/sqlite3:latest
              imagePullPolicy: Always
              env:
                - name: TZ
                  value: Europe/Madrid
              command:
                - /bin/sh
              args:
                - -c
                - "/usr/bin/sqlite3 /data/db.sqlite3 .backup '/data/backups/db-$(date +%Y%m%d-%H%M).sqlite3'"
              volumeMounts:
                - mountPath: /data
                  name: bitwardenrs-config
          volumes:
            - name: bitwardenrs-config
              persistentVolumeClaim:
                claimName: bitwardenrs-config
