---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bitwardenrs
spec:
  chart:
    spec:
      # renovate: registryUrl=https://gissilabs.github.io/charts/
      chart: bitwardenrs
      version: 0.1.5
      sourceRef:
        kind: HelmRepository
        name: gissilabs
        namespace: flux-system
  install:
    remediation:
      retries: 3
  interval: 5m0s
  values:
    image:
      repository: bitwardenrs/server
      tag: 1.19.0

    bitwardenrs:
      admin:
        enabled: false
      allowSignups: false
      domain: https://pw.perezmz.com
      log:
        file: /data/bitwardenrs.log
        level: warn
      smtp:
        enabled: false
      yubico:
        enabled: false

    database:
      type: sqlite
      wal: true

    ingress:
      annotations:
        kubernetes.io/ingress.class: nginx
      enabled: true
      host: pw.perezmz.com
      tls:
        - hosts:
            - pw.perezmz.com
          secretName: perezmz-com-tls

    persistence:
      enabled: true
      existingClaim: bitwardenrs-config

    podSecurityContext:
      fsGroup: 1001

    securityContext:
      runAsGroup: 1001
      runAsUser: 1001
