---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bitwardenrs
spec:
  chart:
    spec:
      # renovate: registryUrl=https://gissilabs.github.io/charts/
      chart: bitwardenrs
      version: 0.3.0
      sourceRef:
        kind: HelmRepository
        name: gissilabs
        namespace: flux-system
  install:
    remediation:
      retries: 3
  interval: 5m0s
  values:
    image:
      repository: vaultwarden/server
      tag: 1.22.1

    bitwardenrs:
      admin:
        enabled: false
      allowSignups: false
      domain: https://pw.perezmz.com
      log:
        file: /data/bitwardenrs.log
        level: warn
      smtp:
        enabled: false
      yubico:
        enabled: false

    database:
      type: sqlite
      wal: true

    ingress:
      enabled: true
      ingressClassName: traefik
      host: pw.perezmz.com
      tls:
        - secretName: perezmz-com-tls

    persistence:
      enabled: true
      existingClaim: bitwardenrs-config

    podSecurityContext:
      fsGroup: 65534

    securityContext:
      runAsGroup: 65534
      runAsUser: 65534
