---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  chart:
    spec:
      # renovate: registryUrl=https://charts.jetstack.io
      chart: cert-manager
      version: v1.2.0
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
  install:
    remediation:
      retries: 3
  interval: 5m0s
  values:
    cainjector:
      replicaCount: 1
    extraArgs:
      - --dns01-recursive-nameservers=1.1.1.1:53
      - --dns01-recursive-nameservers-only
    installCRDs: false
    podDnsConfig:
      nameservers:
        - 1.1.1.1
        - 8.8.8.8
    podDnsPolicy: None
    prometheus:
      enabled: true
      servicemonitor:
        enabled: false
