apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
spec:
  releaseName: external-dns
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: external-dns
      version: 4.5.4
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    logLevel: debug
    provider: coredns
    coredns:
      etcdEndpoints: http://etcd:2379
    domainFilters:
    - perezmz.com
    - claywith.me
    createSecret: true
    crd:
      create: true