---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: media
spec:
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: sonarr
      version: 9.0.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 5m0s
  install:
    remediation:
      retries: 3
  values:
    image:
      repository: ghcr.io/k8s-at-home/sonarr
      tag: v3.0.4.1126

    env:
      TZ: Europe/Madrid

    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx

        nginx.ingress.kubernetes.io/auth-url: "http://authelia.default.svc.cluster.local:9091/api/verify"
        nginx.ingress.kubernetes.io/auth-signin: "https://login.perezmz.com"
      hosts:
        - host: sonarr.perezmz.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - sonarr.perezmz.com
          secretName: perezmz-com-tls

    additionalVolumes:
      - name: data
        persistentVolumeClaim:
          claimName: media-data
      - name: storage
        persistentVolumeClaim:
          claimName: media-storage

    additionalVolumeMounts:
      - name: data
        mountPath: /config
        subPath: sonarr
      - name: data
        mountPath: /downloads
        subPath: downloads
      - name: storage
        mountPath: /tv
        subPath: media/tv

    podSecurityContext:
      runAsUser: 1001
      runAsGroup: 1001
      fsGroup: 1001
