---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flood
spec:
  releaseName: flood
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: flood
      version: 2.3.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    image:
      repository: jesec/flood
      tag: 4.3.1
      pullPolicy: Always

    env:
      FLOOD_OPTION_RUNDIR: /data
      FLOOD_OPTION_AUTH: "none"
      FLOOD_OPTION_QBUSER: ""
      FLOOD_OPTION_QBPASS: ""
      FLOOD_OPTION_QBURL: "http://qbittorrent.media.svc.cluster.local:8080"

    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: internal

        nginx.ingress.kubernetes.io/auth-url: "http://authelia.ingress-system.svc.cluster.local:9091/api/verify"
        nginx.ingress.kubernetes.io/auth-signin: "https://login.perezmz.com"
      hosts:
        - host: flood.perezmz.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - flood.perezmz.com
          secretName: perezmz-com-tls

    persistence:
      data:
        enabled: true
        existingClaim: media-data
        subPath: flood

    securityContext:
      runAsGroup: 1001
      runAsUser: 1001

    podSecurityContext:
      fsGroup: 1001
