apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: victoria-metrics-operator
spec:
  releaseName: victoria-metrics-operator
  chart:
    spec:
      # renovate: registryUrl=https://victoriametrics.github.io/helm-charts/
      chart: victoria-metrics-operator
      version: 0.1.5
      sourceRef:
        kind: HelmRepository
        name: victoria-metrics
        namespace: flux-system
  install:
    remediation:
      retries: 3
  interval: 5m
  values:
    createCRD: false