apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: victoria-metrics-operator
spec:
  releaseName: victoria-metrics-operator
  chart:
    spec:
      chart: victoria-metrics-operator
      version: 0.1.5
      sourceRef:
        kind: HelmRepository
        name: victoria-metrics
        namespace: flux-system
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    createCRD: false