---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: radarr
  namespace: media
spec:
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: radarr
      version: 8.4.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 5m0s
  install:
    remediation:
      retries: 3
  values:
    image:
      repository: ghcr.io/hotio/radarr
      tag: nightly-3.1.0.4612

    env:
      TZ: Europe/Madrid
      PUID: 1001
      PGID: 1001

    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx

        nginx.ingress.kubernetes.io/auth-url: "http://authelia.default.svc.cluster.local:9091/api/verify"
        nginx.ingress.kubernetes.io/auth-signin: "https://login.perezmz.com"
      hosts:
        - host: radarr.perezmz.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - radarr.perezmz.com
          secretName: perezmz-com-tls

    additionalVolumes:
      - name: data
        persistentVolumeClaim:
          claimName: media-data
      - name: storage
        persistentVolumeClaim:
          claimName: media-storage

    additionalVolumeMounts:
      - name: data
        mountPath: /config
        subPath: radarr
      - name: data
        mountPath: /downloads
        subPath: downloads
      - name: storage
        mountPath: /movies
        subPath: media/movies
