---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: radarr
  namespace: media
spec:
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: radarr
      version: 12.3.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 5m0s
  install:
    remediation:
      retries: 3
  values:
    image:
      repository: ghcr.io/k8s-at-home/radarr
      tag: v3.2.2.5080

    env:
      TZ: Europe/Madrid

    ingress:
      main:
        enabled: true
        ingressClassName: traefik
        annotations:
          traefik.ingress.kubernetes.io/router.middlewares: traefik-forward-auth@kubernetescrd
        hosts:
          - host: radarr.perezmz.com
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: perezmz-com-tls

    persistence:
      config:
        enabled: true
        type: hostPath
        hostPath: /data/radarr
        mountPath: /config
      downloads:
        enabled: true
        type: hostPath
        hostPath: /data/downloads
        mountPath: /downloads
      movies:
        enabled: true
        type: hostPath
        hostPath: /mnt/storage/media/movies
        mountPath: /movies

    podSecurityContext:
      runAsUser: 65534
      runAsGroup: 65534
      fsGroup: 65534

    prometheus:
      podMonitor:
        enabled: true
        interval: 10m
        scrapeTimeout: 2s

    additionalContainers:
    - name: exportarr
      image: ghcr.io/onedr0p/exportarr:v0.6.1
      imagePullPolicy: IfNotPresent
      args: ["exportarr", "radarr"]
      env:
      - name: PORT
        value: "32123"
      - name: URL
        value: "http://localhost"
      - name: CONFIG
        value: "/config/config.xml"
      - name: ENABLE_UNKNOWN_QUEUE_ITEMS
        value: "true"
      - name: ENABLE_ADDITIONAL_METRICS
        value: "true"
      ports:
      - name: exportarr
        containerPort: 32123
      volumeMounts:
      - name: config
        mountPath: /config
        readOnly: true
