---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: radarr
  namespace: media
spec:
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: radarr
      version: 12.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 5m0s
  install:
    remediation:
      retries: 3
  values:
    image:
      repository: ghcr.io/k8s-at-home/radarr
      tag: v3.2.2.5080

    env:
      TZ: Europe/Madrid

    ingress:
      main:
        enabled: true
        ingressClassName: traefik
        annotations:
          traefik.ingress.kubernetes.io/router.middlewares: traefik-forward-auth@kubernetescrd
        hosts:
          - host: radarr.perezmz.com
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: perezmz-com-tls

    persistence:
      config:
        enabled: true
        type: hostPath
        hostPath: /data/radarr
        mountPath: /config
      downloads:
        enabled: true
        type: hostPath
        hostPath: /data/downloads
        mountPath: /downloads
      movies:
        enabled: true
        type: hostPath
        hostPath: /mnt/storage/media/movies
        mountPath: /movies

    podSecurityContext:
      runAsUser: 1001
      runAsGroup: 1001
      fsGroup: 1001
