---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: firefly-iii
spec:
  chart:
    spec:
      chart: ./charts/firefly-iii
      version: 1.x
      sourceRef:
        kind: GitRepository
        name: my-helm-charts
        namespace: flux-system
  interval: 5m0s
  install:
    remediation:
      retries: 3
  values:
    image:
      repository: jc5x/firefly-iii
      tag: version-5.4.6

    envFrom:
      - secretRef:
          name: firefly-iii-config

    env:
      DB_HOST: mariadb.default.svc.cluster.local
      DB_PORT: 3306
      DB_CONNECTION: mysql
      APP_URL: https://firefly.perezmz.com

    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        traefik.ingress.kubernetes.io/service.serversscheme: https
      hosts:
        - host: firefly.perezmz.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: perezmz-com-tls

    persistence:
      data:
        enabled: true
        existingClaim: default-data
        subPath: firefly-iii

    podSecurityContext:
      fsGroup: 1001
