---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: websites-source
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: ssh-credentials
  url: ssh://git@github.com/gperezmz/k8s-websites
  ignore: |
    # exclude file extensions
    /**/.gitignore
    /**/*.md
    /**/*.txt
    /**/.sops.yaml
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: websites
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  interval: 10m0s
  path: ./
  prune: true
  sourceRef:
    kind: GitRepository
    name: websites-source
  validation: client
