---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: external-dns-crd-source
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://github.com/kubernetes-sigs/external-dns.git
  ref:
    semver: ">=v0.7.6 <0.8.0"
  ignore: |
    # exclude all
    /*
    # include deploy crds manifest
    !/docs/contributing/crd-source/crd-manifest.yaml
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: external-dns-crd
  namespace: flux-system
spec:
  interval: 5m0s
  prune: false
  sourceRef:
    kind: GitRepository
    name: external-dns-crd-source
  timeout: 2m
