---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flood
  namespace: media
spec:
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: flood
      version: 5.3.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 5m0s
  install:
    remediation:
      retries: 3
  values:
    image:
      repository: jesec/flood
      tag: 4.6.1
      pullPolicy: Always

    env:
      FLOOD_OPTION_RUNDIR: /data
      FLOOD_OPTION_AUTH: "none"
      FLOOD_OPTION_QBUSER: ""
      FLOOD_OPTION_QBPASS: ""
      FLOOD_OPTION_QBURL: "http://qbittorrent.media.svc.cluster.local:8080"

    ingress:
      main:
        enabled: true
        ingressClassName: traefik
        annotations:
          traefik.ingress.kubernetes.io/router.middlewares: traefik-forward-auth@kubernetescrd
        hosts:
          - host: flood.perezmz.com
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: perezmz-com-tls

    persistence:
      data:
        enabled: true
        type: hostPath
        hostPath: /data/flood
        mountPath: /data

    securityContext:
      runAsGroup: 1001
      runAsUser: 1001

    podSecurityContext:
      fsGroup: 1001
