---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
  namespace: traefik
  labels:
    name: traefik-config
data:
  dyn.yaml: |
    # https://doc.traefik.io/traefik/https/tls/
    tls:
      stores:
        default:
          defaultCertificate:
            certFile: /certs/tls.crt
            keyFile: /certs/tls.key
