apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: coredns-local
  namespace: kube-system
spec:
  dependsOn:
    - name: etcd
      namespace: kube-system
  chart:
    spec:
      # renovate: registryUrl=https://coredns.github.io/helm
      chart: coredns
      version: 1.14.1
      sourceRef:
        kind: HelmRepository
        name: coredns
        namespace: flux-system
  interval: 5m0s
  install:
    remediation:
      retries: 3
  values:
    rbac:
      create: true
    replicaCount: 1
    isClusterService: false
    serviceType: LoadBalancer
    service:
      externalIPs:
        - 192.168.2.100
      externalTrafficPolicy: Local
    servers:
      - zones:
          - zone: perezmz.com.
            scheme: dns://
          - zone: claywith.me
            scheme: dns://
        port: 53
        plugins:
          - name: errors
          - name: health
            configBlock: |-
              lameduck 5s
          - name: ready
          - name: kubernetes
            parameters: cluster.local in-addr.arpa ip6.arpa
            configBlock: |-
              pods insecure
              fallthrough in-addr.arpa ip6.arpa
              ttl 30
          - name: prometheus
            parameters: 0.0.0.0:9153
          - name: forward
            parameters: . /etc/resolv.conf
          - name: cache
            parameters: 30
          - name: loop
          - name: reload
          - name: loadbalance
          - name: etcd
            parameters: perezmz.com claywith.me
            configBlock: |-
              stubzones
              path /skydns
              endpoint http://etcd:2379
