---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: perezmz-com
  namespace: cert-manager
  annotations:
    reflector.v1.k8s.emberstack.com/secret-reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/secret-reflection-auto-enabled: "true"
spec:
  commonName: perezmz.com
  dnsNames:
    - perezmz.com
    - "*.perezmz.com"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production
  secretName: perezmz-com-tls
