---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkding
spec:
  chart:
    spec:
      chart: ./charts/linkding
      version: 1.x
      sourceRef:
        kind: GitRepository
        name: my-helm-charts
        namespace: flux-system
  interval: 5m0s
  install:
    remediation:
      retries: 3
  values:
    image:
      repository: sissbruecker/linkding
      tag: 1.4.0

    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        traefik.ingress.kubernetes.io/router.middlewares: traefik-forward-auth@kubernetescrd
      hosts:
        - host: linkding.perezmz.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: perezmz-com-tls

    persistence:
      data:
        enabled: true
        existingClaim: default-data
        subPath: linkding

    podSecurityContext:
      runAsUser: 1001
      runAsGroup: 1001
      fsGroup: 1001
