---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: mariadb-backup
spec:
  schedule: "0 8,20 * * *"
  failedJobsHistoryLimit: 3
  successfulJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          securityContext:
            runAsGroup: 65534
            runAsUser: 65534
            fsGroup: 65534
          initContainers:
            - name: rclone-conf
              image: alpine/git:v2.30.2
              env:
                - name: GITHUB_TOKEN
                  valueFrom:
                    secretKeyRef:
                      key: github-token
                      name: github-token
              command:
                - /bin/sh
                - -ec
                - |
                  set -o nounset
                  set -o errexit
                  if [ -z "${GITHUB_TOKEN}" ]; then
                    printf "%s - Error - Missing GITHUB_TOKEN environment variable" "$(date -u)"
                    exit 1
                  fi
                  git clone --depth 1 "https://${GITHUB_TOKEN}:x-oauth-basic@github.com/gperezmz/rclone-config.git" /shared/rclone-conf
                  exit 0
              volumeMounts:
                - mountPath: /shared
                  name: shared
            - name: busybox-shell
              image: busybox
              args:
                - /bin/sh
                - -c
                - '(mkdir /data/backups || true) && (rm /data/backups/* || true)'
              volumeMounts:
                - mountPath: /data
                  name: default-data
                  subPath: mariadb
            - name: rclone-cleanup
              image: rclone/rclone:1.55
              env:
                - name: TZ
                  value: UTC
              command:
                - rclone
              args:
                - -v
                - --config
                - /shared/rclone-conf/rclone.conf
                - --min-age
                - 7d
                - delete
                - onedrive-crypt:/mariadb
              volumeMounts:
                - mountPath: /shared
                  name: shared
            - name: mariadb
              image: bitnami/mariadb:10.5.11
              imagePullPolicy: Always
              env:
                - name: TZ
                  value: UTC
                - name: MARIADB_HOSTNAME
                  value: mariadb.default.svc.cluster.local
                - name: MARIADB_ROOT_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: mariadb-root-password
                      name: mariadb-passwords
                - name: DATABASES
                  value: claywithme
              command:
                - /bin/sh
              args:
                - -c
                - "mysqldump --host=${MARIADB_HOSTNAME} --user=root --password=${MARIADB_ROOT_PASSWORD} --databases ${DATABASES} > /data/backups/backup-$(date +%Y%m%d-%H%M).sql"
              volumeMounts:
                - mountPath: /data
                  name: default-data
                  subPath: mariadb
          containers:
            - name: rclone
              image: rclone/rclone:1.55
              env:
                - name: TZ
                  value: UTC
              command:
                - rclone
              args:
                - -v
                - --config
                - /shared/rclone-conf/rclone.conf
                - copy
                - --ignore-errors
                - /data/backups
                - onedrive-crypt:/mariadb
              volumeMounts:
                - mountPath: /shared
                  name: shared
                - mountPath: /data
                  name: default-data
                  subPath: mariadb
          volumes:
            - name: default-data
              persistentVolumeClaim:
                claimName: default-data
            - name: shared
              emptyDir: {}
