---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mariadb
spec:
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: mariadb
      version: 9.3.11
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    auth:
      existingSecret: mariadb-passwords
      forcePassword: true
      usePasswordFiles: true

    primary:
      persistence:
        existingClaim: default-data
        subPath: mariadb
