---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unifi
spec:
  releaseName: unifi
  chart:
    spec:
      chart: ./charts/unifi
      version: "1.0.x"
      sourceRef:
        kind: GitRepository
        name: my-helm-charts
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    image:
      repository: ghcr.io/linuxserver/unifi-controller
      tag: 6.0.43-ls94

    env:
      PUID: 1001
      PGID: 1001
      TZ: Europe/Madrid

    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: internal

        nginx.ingress.kubernetes.io/backend-protocol: HTTPS
      hosts:
        - host: unifi.perezmz.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - unifi.perezmz.com
          secretName: perezmz-com-tls

    persistence:
      config:
        enabled: true
        existingClaim: default-data
        subPath: unifi

    podSecurityContext:
      fsGroup: 1001
