---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authelia
spec:
  chart:
    spec:
      chart: ./charts/authelia
      version: 1.x
      sourceRef:
        kind: GitRepository
        name: my-helm-charts
        namespace: flux-system
  dependsOn:
    - name: redis
      namespace: default
  install:
    remediation:
      retries: 3
  interval: 5m0s0s
  values:
    additionalVolumeMounts:
      - mountPath: /app/secrets
        name: secrets
        readOnly: true

    additionalVolumes:
      - name: secrets
        secret:
          items:
            - key: jwt_secret
              path: jwt_secret
            - key: session_secret
              path: session_secret
          secretName: authelia-secrets

    env:
      AUTHELIA_JWT_SECRET_FILE: /app/secrets/jwt_secret
      AUTHELIA_SESSION_SECRET_FILE: /app/secrets/session_secret
      TZ: Europe/Madrid

    image:
      repository: authelia/authelia
      tag: 4.26.0

    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
      hosts:
        - host: login.perezmz.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - login.perezmz.com
          secretName: perezmz-com-tls

    persistence:
      config:
        enabled: true
        existingClaim: default-data
        subPath: authelia

    podSecurityContext:
      fsGroup: 1001

    securityContext:
      runAsGroup: 1001
      runAsUser: 1001
