apiVersion: v1
kind: PersistentVolume
metadata:
  name: vmsingle-main-data
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  hostPath:
    path: /data/victoria-metrics
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage