apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
spec:
  releaseName: plex
  chart:
    spec:
      chart: ./charts/plex
      version: '1.0.x'
      sourceRef:
        kind: GitRepository
        name: my-helm-charts
        namespace: flux-system
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    image:
      repository: plexinc/pms-docker
      tag: plexpass
      pullPolicy: Always

    env:
      TZ: Europe/Madrid
      PLEX_UID: 1001
      PLEX_GID: 1001
      HOSTNAME: plex.perezmz.com
      ADVERTISE_IP: https://plex.perezmz.com:443/,http://192.168.2.21:32400/
      ALLOWED_NETWORKS: 192.168.0.0/22,10.42.0.0/16

    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: external

        nginx.ingress.kubernetes.io/configuration-snippet: |
          proxy_set_header Host    $server_addr;
          proxy_set_header Referer $server_addr;
          proxy_set_header Origin  $server_addr; 
      hosts:
        - host: plex.perezmz.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - plex.perezmz.com
          secretName: perezmz-com-tls

    additionalVolumes:
    - name: data
      persistentVolumeClaim:
        claimName: media-data
    - name: storage
      persistentVolumeClaim:
        claimName: media-storage

    additionalVolumeMounts:
    - name: data
      mountPath: /config
      subPath: plex
    - name: data
      mountPath: /transcode
      subPath: plex-transcode
    - name: storage
      mountPath: /data
      subPath: media

    podSecurityContext:
      fsGroup: 1001