# Source: victoria-metrics-agent/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vmagent-main-clusterrole
  labels:
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/instance: main
    app.kubernetes.io/name: vmagent
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
      - nodes/proxy
      - nodes/metrics
      - services
      - endpoints
      - pods
      - endpointslices
      - configmaps
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - networking.k8s.io
      - extensions
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
  - nonResourceURLs:
      - /metrics
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resourceNames:
      - vmagent-main
    resources:
      - podsecuritypolicies
    verbs:
      - use
  - apiGroups:
      - policy
    resourceNames:
      - vmagent-main
    resources:
      - podsecuritypolicies
    verbs:
      - use
