---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: ssh://git@github.com/gperezmz/k8s-gitops
  ignore: |
    # exclude all
    /*
    # include
    !/cluster/flux-system
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: crds
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: ssh://git@github.com/gperezmz/k8s-gitops
  ignore: |
    # exclude all
    /*
    # include
    !/cluster/crds/
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: cluster
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: ssh://git@github.com/gperezmz/k8s-gitops
  ignore: |
    # exclude all
    /*
    # include
    !/cluster/
    # exclude flux-system and crds
    /cluster/flux-system/
    /cluster/crds/
