---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: flux-system-git-chart-repositories
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./cluster/flux-system/git-chart-repositories
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: flux-system-helm-repositories
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./cluster/flux-system/helm-chart-repositories
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: my-websites
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: ssh-credentials
  url: ssh://git@github.com/gperezmz/k8s-websites
  ignore: |
    # exclude file extensions
    /**/.gitignore
    /**/*.md
    /**/*.txt