---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: flux-system-git-repositories
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./cluster/flux-system/git-repositories
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: flux-system-git-chart-repositories
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./cluster/flux-system/git-chart-repositories
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: flux-system-helm-repositories
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./cluster/flux-system/helm-chart-repositories
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: flux-system-bootstrap
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: ssh://git@github.com/gperezmz/k8s-gitops
  ignore: |
    # exclude all
    /*
    # include bootstrap
    !/bootstrap
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: flux-system-root
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: ssh://git@github.com/gperezmz/k8s-gitops
  ignore: |
    # exclude flux-system and bootstrap
    cluster/
    bootstrap/
    .github/
    cni/
    .gitignore
    /**/*.md
    .sops.yaml
    media/
    monitoring-system/
    kube-system/
    default/
    ingress-system/
