---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bazarr
spec:
  releaseName: bazarr
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: bazarr
      version: 5.3.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    image:
      repository: ghcr.io/hotio/bazarr
      tag: release-0.9.0.8

    env:
      TZ: Europe/Madrid
      PUID: 1001
      PGID: 1001

    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: internal

        nginx.ingress.kubernetes.io/auth-url: "http://authelia.ingress-system.svc.cluster.local:9091/api/verify"
        nginx.ingress.kubernetes.io/auth-signin: "https://login.perezmz.com"
      hosts:
        - host: bazarr.perezmz.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - bazarr.perezmz.com
          secretName: perezmz-com-tls

    additionalVolumes:
      - name: data
        persistentVolumeClaim:
          claimName: media-data
      - name: storage
        persistentVolumeClaim:
          claimName: media-storage

    additionalVolumeMounts:
      - name: data
        mountPath: /config
        subPath: bazarr
      - name: storage
        mountPath: /movies
        subPath: media/movies
      - name: storage
        mountPath: /tv
        subPath: media/tv
