---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: claywithme
  namespace: websites
spec:
  dependsOn:
    - namespace: default
      name: mariadb
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: wordpress
      version: 11.0.17
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 5m0s
  install:
    remediation:
      retries: 3
  values:
    ingress:
      enabled: true
      ingressClassName: traefik

    wordpressSkipInstall: true
    wordpressScheme: https
    wordpressAutoUpdateLevel: none
    wordpressPlugins: none

    livenessProbe:
      httpGet:
        httpHeaders:
          - name: X-Forwarded-Proto
            value: https

    readinessProbe:
      httpGet:
        httpHeaders:
          - name: X-Forwarded-Proto
            value: https

    allowOverrideNone: true
    htaccessPersistenceEnabled: true

    service:
      type: ClusterIP

    persistence:
      existingClaim: claywithme-data

    volumePermissions:
      enabled: true

    extraVolumeMounts:
      - name: apache-config
        subPath: real_ip.conf
        mountPath: /opt/bitnami/apache/conf/vhosts/real_ip.conf

    extraVolumes:
      - name: apache-config
        configMap:
          name: claywithme-apache-config

    mariadb:
      enabled: false

    externalDatabase:
      host: mariadb.default.svc.cluster.local
  valuesFrom:
    - kind: Secret
      name: claywithme-helm-values
