apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: iso-win10
spec:
  source:
    http:
      url: http://192.168.1.48:8000/windows-10.iso
  pvc:
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 5Gi
    volumeName: iso-win10
    storageClassName: local-storage
