apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: iso-win10
spec:
  source:
    upload: {}
  pvc:
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 5Gi
    volumeName: iso-win10
    storageClassName: local-storage
