apiVersion: v1
data:
  dns-token: ENC[AES256_GCM,data:dqBtblgZrSakLkYKVq4kHM2T5ug4NLXvVWlB08btOXZMZc9XyFui1S0LUD22beLooJGlPacDpp0=,iv:/0/xPFI8jMOiBNho7SoOxc+r8C/cB4zx/t6tjNUQpqw=,tag:lukXFXIXM1BJTXfi/j9r/w==,type:str]
kind: Secret
metadata:
  name: cloudflare
sops:
  azure_kv: []
  encrypted_regex: ^(data|stringData)$
  gcp_kms: []
  hc_vault: []
  kms: []
  lastmodified: "2021-01-12T01:46:06Z"
  mac: ENC[AES256_GCM,data:v/EY3Us7b8jC5ZHMrAZYlTRa95u4Gz0R4DTOSWN8GDjN+Tthypi0SnQ7nFLrhewzy9b2Yx47esvjvfPIkDWPEaJDPeb0NwrRnAr56jPNewi8P9I61xJtX+EQ2uO1492AB3Wod8BoPvDU2+FYBkdy444vpuWuDTjaH6m5S5ViPnc=,iv:bD0t9Nk+mNaXk64z2jJPO1z6icncsgQuiPwN4tI80Bk=,tag:OxYmeGZrf+oWN2CaIaegZQ==,type:str]
  pgp:
    - created_at: "2021-01-12T01:46:05Z"
      enc: "-----BEGIN PGP MESSAGE-----\r\n\r\nhQGMAz2OwhEturU+AQwAsF7X0qXSH7uE4IpJrjPHC5jq/ARd76eUDvM3WT/PU53m\r\nIMvX51niFgGFyUAmnmmBO45EFX3VBi/0pyGSUA9N+C9oB7bprQOZ7s3/5+wKzJN4\r\ntRXOiHtBkgwvx37Zo5ClHnijJykgKOcH1DvFP6Q711Z7vrMw7rA17oZ/NBRkr3k0\r\nwMsChPubgN0wzrogNGk+Qa5L9cqdcdm6FIpTdjBZQyeyJFvKReWK9dIo0K3J7rL6\r\n4CvcVp5YBm+S4dwNj02ynDnrouvLfQHn9qQby0KyDV6nV3PddaRPAESuerUnZu5l\r\n7hYkvP1b7KvHV/ULXaUzF5SMV5e6Mx/vGNBZpXt9Z87NQfFQ5YNhUBYPxKHHoYsY\r\np+IwJ8rH6HIf1gHhn0VPxiAmT9CSSHZSzpGfjR2zS/phcba3E7r2faSlR9qniIuS\r\nAm3XyX8y/+ewty9UpSB1o1Ow+L5FeeT90Sz+nEdxZABfNtpwjA61s7uracvDtFEr\r\nGbwIwJ4KL3y+vSmtBVoH0lwBW6UDt0ukII+LBithSv6rWo/zU7WmXyFGHvfqwhNn\r\nsY90J0VP/NZ89UTpDNdCLbaCwqEZBewwXWen6T5/9OnQ6FwS/27mteyWmOZjYaqn\r\nkxLtRH1MMlTH9jh1lg==\r\n=9WTm\r\n-----END PGP MESSAGE-----\r\n"
      fp: B95DBC80D9BD192B0811AC61BB73E1527E549D6C
  version: 3.6.1
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    email: gperezmz@outlook.com
    privateKeySecretRef:
      name: letsencrypt-production
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              key: dns-token
              name: cloudflare
            email: gperezmz@outlook.com
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    email: gperezmz@outlook.com
    privateKeySecretRef:
      name: letsencrypt-staging
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              key: dns-token
              name: cloudflare
            email: gperezmz@outlook.com
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: claywith-me
  annotations:
    reflector.v1.k8s.emberstack.com/secret-reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/secret-reflection-auto-enabled: "true"
spec:
  commonName: claywith.me
  dnsNames:
    - claywith.me
    - "*.claywith.me"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production
  secretName: claywith-me-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: perezmz-com
  annotations:
    reflector.v1.k8s.emberstack.com/secret-reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/secret-reflection-auto-enabled: "true"
spec:
  commonName: perezmz.com
  dnsNames:
    - perezmz.com
    - "*.perezmz.com"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production
  secretName: perezmz-com-tls
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
      version: v1.1.0
  install:
    remediation:
      retries: 3
  interval: 5m
  releaseName: cert-manager
  values:
    cainjector:
      replicaCount: 1
    extraArgs:
      - --dns01-recursive-nameservers=1.1.1.1:53
      - --dns01-recursive-nameservers-only
    installCRDs: true
    podDnsConfig:
      nameservers:
        - 1.1.1.1
        - 8.8.8.8
    podDnsPolicy: None
